[workspace]
authors = ["Guanqiao Feng <fengguanqiao321@gmail.com>"]
channels = ["conda-forge"]
name = "PMLB_chatbot"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test_cases = "python3 -m scripts.test_list_pmlb_cases"
test_specimen = "python3 -m scripts.test_all_pmlb_specimen"
test_all = "python3 -m scripts.test_all_schema"
test_llm_call = "python3 -m scripts.test_llm_call"
chat = "python interface/cli.py"

[dependencies]
python = "3.11.*"
requests = ">=2.32.4,<3"
python-dotenv = ">=1.1.1,<2"
pip = ">=25.2,<26"
